language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.2
  # - 1.6.0-rc.0
otp_release:
  - 18.3
  - 19.3
  - 20.0
matrix:
  exclude:
    - otp_release: 20.0
      elixir: 1.3.4
notifications:
  recipients:
    - austin@zieglers.ca
